name: Publish Maven package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD
      - name: Publish package
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}